[waveshare-esp32-c6-lcd-147]
extends = esp32c6_base
board = esp32-c6-devkitm-1
board_build.partitions = min_spiffs.csv ; get around 4mb flash limit
build_flags =
  ${esp32c6_base.build_flags}
  -I variants/waveshare-esp32-c6-lcd-147
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D P_LORA_SCLK=5
  -D P_LORA_MISO=18
  -D P_LORA_MOSI=19
  -D P_LORA_NSS=20
  -D P_LORA_DIO_1=23
  -D P_LORA_BUSY=12
  -D P_LORA_RESET=13
  -D SX126X_RXEN=
  -D PIN_USER_BTN=9
  -D SX126X_DIO2_AS_RF_SWITCH=true
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=22
  -D DISABLE_WIFI_OTA=1

build_src_filter = ${esp32c6_base.build_src_filter}
  +<../variants/waveshare-esp32-c6-lcd-147>
  +<WaveshareESP32C6LCDBoard.cpp>

[env:waveshare-esp32-c6-lcd-147-companion-radio-ble]
extends = waveshare-esp32-c6-lcd-147
build_flags = ${waveshare-esp32-c6-lcd-147.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
  -D ENABLE_PRIVATE_KEY_IMPORT=1
  -D ENABLE_PRIVATE_KEY_EXPORT=1
  -I examples/companion_radio/ui-new
  -D ST7789
  -D DISPLAY_CLASS=ST7789Display
  -D HELTEC_VISION_MASTER_T190
  -D PIN_TFT_SDA=6
  -D PIN_TFT_SCL=7
  -D PIN_TFT_CS=14
  -D PIN_TFT_DC=15
  -D PIN_TFT_RST=21
  -D PIN_TFT_VDD_CTL=-1
  -D PIN_TFT_LEDA_CTL=22
  -D PIN_TFT_LEDA_CTL_ACTIVE=HIGH
build_src_filter = ${waveshare-esp32-c6-lcd-147.build_src_filter}
  +<helpers/esp32/*.cpp>
  -<helpers/esp32/ESPNOWRadio.cpp>
  +<helpers/ui/ST7789Display.cpp>
  +<helpers/ui/OLEDDisplay.cpp>
  +<helpers/ui/OLEDDisplayFonts.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>

lib_deps =
  ${waveshare-esp32-c6-lcd-147.lib_deps}
  densaugeo/base64 @ ~1.4.0
  adafruit/Adafruit GFX Library @ ^1.12.1
